### ISSUE TITLE
missing lab

### ISSUE THREAD

**Issue by mcavaioni** [learn-co-curriculum/manipulating-hashes#15]
This lesson asks to fork a lab in order to code the solution in the lib/first_challenge.rb.
The fork to the lab is missing

**Comment by AnnJohn** [comment]
Thanks at @mcavaioni for raising the issue. We'll fix it as soon as we can.

**Comment by AnnJohn** [comment]
Fixed

**Comment by sammarcus** [comment]
(@AnnJohn: it's fixed on track ID 10415 as well)

**Comment by AnnJohn** [comment]
Thanks @sammarcus !
