### ISSUE TITLE
Issue with .MIN example

### ISSUE THREAD

**Issue by annafractuous** [learn-co-curriculum/manipulating-hashes#17]
The current .min example is: 

.MIN
You can use the .min method on a hash to return the key/value pair that contains that lowest value:
food_items = {apples: 45, pears: 12}
food_items.min
=> [:apples, 45]

But .min returns the key/value pair with the lowest key, not the lowest value. The intention here would be to return [:pears, 12] but we instead get [:apples, 45].

**Comment by AnnJohn** [comment]
hi @annafractuous sorry for the delay and thanks for raising this issue. We'll look into this as soon as we can.

**Comment by AnnJohn** [comment]
clarified the definition @annafractuous. thanks again for raising the issue!
