### ISSUE TITLE
order of hash curriculum

### ISSUE THREAD

**Issue by sparkbold** [learn-co-curriculum/manipulating-hashes#27]
The concept introduces here in the section of return value of nested lab should be included in the introduction to first nested hash lab. The example is excellent! Got so much trouble in the first nested lab where I didn't know the concept of hash[key_1st_tier][key_2nd_tier][key_3rd_tier] return value of the 3rd tier key.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
